# Set to true to disable the Grype image scan completely
disabled: false

ignore:
  - vulnerability: CVE-2025-56200
    reason: "No fix available without breaking changes - validator.js URL validation bypass in hapi-openapi/hapi-swagger dependency chain. Fix would require downgrading hapi-openapi to 1.2.6 which is a major breaking change."
  - vulnerability: CVE-2025-46394
    reason: "busybox vulnerability in Alpine base image - no fix available in Alpine 3.22, low severity with minimal risk"
  - vulnerability: CVE-2024-58251
    reason: "busybox/ssl_client vulnerability in Alpine base image - inherent to Alpine Linux, low severity with minimal risk"

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
